[build]
  base = "Med"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle Next.js API routes as Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect all other routes to index for SPA behavior
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# PDF file headers for optimal viewing
[[headers]]
  for = "/cheat-sheets/**/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Range, Content-Type"
    Cache-Control = "public, max-age=86400"
    Accept-Ranges = "bytes"

# Static asset caching
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# General static asset caching
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 